### PR TITLE
Update for conndb.php

### PR DESCRIPTION
**Pull request by DasunNethsara-04**
Bro, use mysqli class directly when you want to connect MySQL database with frontend. Simply you can create a object for mysqli class and pass all the parameters like server IP, username, password and database name.

### CODE REVIEW

**Comment by DasunNethsara-04** [comment]
Let's remake it more efficient and functional after A/Ls

**Comment by HashanSudeera** [comment]
> Bro, use mysqli class directly when you want to connect MySQL database with frontend. Simply you can create a object for mysqli class and pass all the parameters like server IP, username, password and database name.

Bro. I think two ways get same output..MySQLi (object-oriented) and
MySQLi (procedural)..Thank you

**Comment by DasunNethsara-04** [comment]
Yes. You're right. But commonly using the MySQLi (object-oriented).

**Comment by DasunNethsara-04** [comment]
> > Bro, use mysqli class directly when you want to connect MySQL database with frontend. Simply you can create a object for mysqli class and pass all the parameters like server IP, username, password and database name.
> 
> Bro. I think two ways get same output..MySQLi (object-oriented) and MySQLi (procedural)..Thank you

Yes. You're right. But commonly using the MySQLi (object-oriented).

**Comment by HashanSudeera** [comment]
ok bro.♥️

**Pull request closed without merging**
